import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "NEXUS Intelligence terms of service. Platform usage terms, subscription conditions, and legal framework.",
  robots: { index: true, follow: false },
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen pt-28 pb-20 px-6">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center gap-3 mb-6">
          <div className="h-px flex-1 max-w-12 bg-accent-cyan/40" />
          <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-accent-cyan/70">
            Legal
          </span>
        </div>

        <h1 className="text-3xl font-bold tracking-tight text-navy-100 mb-2">
          Terms of Service
        </h1>
        <p className="font-mono text-[10px] text-navy-500 uppercase tracking-wider mb-10">
          Last updated: March 2026
        </p>

        <div className="space-y-8">
          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              1. Acceptance of Terms
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              By accessing or using the NEXUS Intelligence Platform ("Service"),
              you agree to be bound by these Terms of Service. If you do not
              agree to these terms, do not use the Service. These terms apply to
              all users, including visitors, registered users, and subscribers.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              2. Description of Service
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              NEXUS provides signal detection, convergence analysis, and
              AI-driven intelligence synthesis across geopolitical, calendar,
              celestial, market, and open-source intelligence domains. The
              Service is provided on a subscription basis with tiered access
              levels.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              3. Not Financial Advice
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              The Service is an analytical tool, not a financial advisory
              service. All intelligence briefs, signal assessments, trade
              recommendations, and predictions are probabilistic analysis based
              on automated signal processing. They do not constitute financial
              advice, investment recommendations, or solicitations to buy or
              sell any security. You are solely responsible for your own
              investment decisions and should consult qualified financial
              advisors before acting on any information provided by the Service.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              4. Account Responsibilities
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              You are responsible for maintaining the confidentiality of your
              account credentials. You agree to notify us immediately of any
              unauthorised use of your account. Account sharing is prohibited.
              Each subscription grants access to a single user.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              5. Subscription and Payment
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              Paid subscriptions are billed monthly or annually as selected at
              checkout. Payments are processed through Stripe. You may cancel
              your subscription at any time through the billing portal. Refunds
              are handled on a case-by-case basis and are not guaranteed.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              6. Intellectual Property
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              All content, algorithms, methodologies, signal processing logic,
              and intelligence outputs generated by the Service are the
              intellectual property of NEXUS Intelligence. You may not
              reproduce, redistribute, or commercially exploit any outputs of
              the Service without written permission.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              7. Limitation of Liability
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              The Service is provided "as is" without warranty of any kind.
              NEXUS Intelligence shall not be liable for any direct, indirect,
              incidental, or consequential damages arising from your use of the
              Service, including financial losses resulting from trading
              decisions made using information provided by the platform.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              8. Modifications
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              We reserve the right to modify these terms at any time.
              Significant changes will be communicated via email or through the
              platform. Continued use of the Service after modifications
              constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-xs font-semibold uppercase tracking-widest text-navy-200 mb-3">
              9. Governing Law
            </h2>
            <p className="font-sans text-sm text-navy-400 leading-relaxed">
              These terms are governed by and construed in accordance with
              applicable law. Any disputes arising from these terms or the
              Service shall be resolved through binding arbitration.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
